export const REQUESTED_TOKEN = "REQUESTED_TOKEN";
export const RECEIVED_TOKEN = "RECEIVED_TOKEN";

export const REQUESTED_MOVIE = "REQUESTED_MOVIE";
export const RECEIVED_MOVIE = "RECEIVED_MOVIE";

export const REQUESTED_UPCOMING_MOVIES = "REQUESTED_UPCOMING_MOVIES";
export const RECEIVED_UPCOMING_MOVIES = "RECEIVED_UPCOMING_MOVIES";

export const REQUESTED_POPULAR_MOVIES = "REQUESTED_POPULAR_MOVIES";
export const RECEIVED_POPULAR_MOVIES = "RECEIVED_POPULAR_MOVIES";

export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const RECEIVED_MOVIES = "RECEIVED_MOVIES";
export const CLEARED_SEARCH_RESULTS = "CLEARED_SEARCH_RESULTS";

export const SHOW_MOVIE = "SHOW_MOVIE";
export const HIDE_MOVIE = "HIDE_MOVIE";

export const SELECT_MOVIE = "SELECT_MOVIE";
export const DESELECT_MOVIE = "DESELECT_MOVIE";